import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

test('SPA assets expose the expected app shell hooks', async () => {
  const html = await readFile('public/index.html', 'utf8');
  const script = await readFile('public/app.js', 'utf8');
  const styles = await readFile('public/styles.css', 'utf8');

  assert.match(html, /<div id="app">/);
  assert.match(html, /app\.js/);
  assert.match(script, /function renderHome/);
  assert.match(script, /home-shell/);
  assert.match(script, /next-tuesday-card/);
  assert.match(script, /presence-card/);
  assert.match(script, /home-summary-card/);
  assert.match(script, /home-drinks-card/);
  assert.match(script, /home-secondary-grid/);
  assert.match(script, /attendance-options/);
  assert.match(script, /guest-stepper-card/);
  assert.match(script, /charge-status-label/);
  assert.match(script, /function renderAttendance/);
  assert.match(script, /function renderPool/);
  assert.match(script, /pool-shell/);
  assert.match(script, /pool-title-card/);
  assert.match(script, /pool-ranking-card/);
  assert.match(script, /ranking-mobile-list/);
  assert.match(script, /pool-admin-section/);
  assert.match(script, /function rankingRowCard/);
  assert.match(script, /function poolStatusLabel/);
  assert.match(script, /function renderDrinks/);
  assert.match(script, /function renderCharges/);
  assert.match(script, /charges-shell/);
  assert.match(script, /charges-title-card/);
  assert.match(script, /finance-summary-card/);
  assert.match(script, /charge-list-card/);
  assert.match(script, /charge-form-card/);
  assert.match(script, /data-charge-filter/);
  assert.match(script, /data-charge-search/);
  assert.match(script, /function bindChargeFilters/);
  assert.match(script, /dinner-shell/);
  assert.match(script, /dinner-title-card/);
  assert.match(script, /dinner-current-card/);
  assert.match(script, /dinner-edit-card/);
  assert.match(script, /function dinnerMemberChoice/);
  assert.match(script, /function bindDinnerMemberSearch/);
  assert.match(script, /function renderAdmin/);
  assert.match(script, /admin-shell/);
  assert.match(script, /admin-title-card/);
  assert.match(script, /admin-summary-card/);
  assert.match(script, /admin-members-card/);
  assert.match(script, /admin-form-card/);
  assert.match(script, /data-member-search/);
  assert.match(script, /data-member-filter/);
  assert.match(script, /function memberCard/);
  assert.match(script, /function bindAdminFilters/);
  assert.match(script, /switch-field/);
  assert.match(script, /function drinkMemberRow/);
  assert.match(script, /function bindDrinkFilters/);
  assert.match(script, /function openDrinkAuditModal/);
  assert.match(script, /data-open-drink-audit/);
  assert.match(script, /data-drink-search/);
  assert.match(script, /data-consumption-filter/);
  assert.match(script, /data-edit-member/);
  assert.match(script, /data-remove-match/);
  assert.match(styles, /\.bottom-nav/);
  assert.match(styles, /\.home-shell/);
  assert.match(styles, /\.next-tuesday-card/);
  assert.match(styles, /\.attendance-options/);
  assert.match(styles, /\.guest-stepper-card/);
  assert.match(styles, /\.home-secondary-grid/);
  assert.match(styles, /\.home-grid/);
  assert.match(styles, /\.pool-shell/);
  assert.match(styles, /\.pool-layout/);
  assert.match(styles, /\.ranking-mobile-list/);
  assert.match(styles, /\.pool-match-card/);
  assert.match(styles, /\.pool-admin-section/);
  assert.match(styles, /\.charges-shell/);
  assert.match(styles, /\.charges-layout/);
  assert.match(styles, /\.finance-summary-grid/);
  assert.match(styles, /\.charge-card/);
  assert.match(styles, /\.charge-actions/);
  assert.match(styles, /\.dinner-shell/);
  assert.match(styles, /\.dinner-layout/);
  assert.match(styles, /\.dinner-member-choice/);
  assert.match(styles, /\.member-choice-list/);
  assert.match(styles, /\.admin-shell/);
  assert.match(styles, /\.admin-layout/);
  assert.match(styles, /\.admin-member-card/);
  assert.match(styles, /\.admin-summary-grid/);
  assert.match(styles, /\.switch-field/);
  assert.match(styles, /\.screen-header/);
  assert.match(styles, /\.command-toolbar/);
  assert.match(styles, /\.modal-backdrop/);
  assert.match(styles, /\.drink-member-row/);
  assert.match(styles, /\.drink-quick-action/);
  assert.match(styles, /@media \(min-width: 860px\)/);
});
